services:
  - name: docker
    image: docker:dind
    privileged: true
    commands:
      - dockerd --host=unix:///dind/docker.sock
    volumes:
      - /opt/woodpeckerci/dind-socket:/dind
    environment:
      DOCKER_HOST: unix:///dind/docker.sock

steps:
  - name: test
    image: docker:cli
    environment:
      DOCKER_HOST: unix:///dind/docker.sock
    volumes:
      - /opt/woodpeckerci/dind-socket:/dind
    commands:
      - ls -l /dind
      - docker version
      - docker build -f Dockerfile.dev -t react_web .
      - docker run --rm react_web npm run test -- --coverage