services:
  - name: docker
    image: docker:28-dind
    privileged: true
    environment:
      DOCKER_TLS_CERTDIR: /dind-certs
    volumes:
      - /opt/woodpeckerci/dind-certs:/dind-certs
    ports:
      - 2376

steps:
  - name: test
    image: docker:28-cli
    environment:
      DOCKER_HOST: tcp://docker:2376
      DOCKER_CERT_PATH: /dind-certs/client
      DOCKER_TLS_VERIFY: "1"
    volumes:
      - /opt/woodpeckerci/dind-certs:/dind-certs
    commands:
      - docker version
      - docker build -f Dockerfile.dev -t react_web .
      - docker run --rm react_web npm run test -- --coverage